package test;

import java.util.List;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link Game} specific assertions - Generated by CustomAssertionGenerator.
 */
public class IntegerListAssert extends AbstractAssert<IntegerListAssert, List<Integer>> {

	/**
	 * Creates a new </code>{@link GameAssert}</code> to make assertions on actual Game.
	 * @param actual the Game we want to make assertions on.
	 */
	public IntegerListAssert(List<Integer> actual) {
		super(actual, IntegerListAssert.class);
	}

	/**
	 * An entry point for GameAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
	 * With a static import, one's can write directly : <code>assertThat(myGame)</code> and get specific assertion with code completion.
	 * @param actual the Game we want to make assertions on.
	 * @return a new </code>{@link GameAssert}</code>
	 */
	public static IntegerListAssert assertThat(List<Integer> actual) {
		return new IntegerListAssert(actual);
	}

}
